#!/bin/bash
apt-get install ruby-dev
gem install bdoc hanna
gem rdoc --all
gem install rails capistrano hpricot

apt-get install libxml2-dev libxslt-dev
gem install nokogiri
apt-get remove libxml2-dev libxslt-dev
apt-get autoremove
