source ~/.vim/vimrc
"========= Alexey Chernikov additions ==============
colorscheme vibrantink
"*** Keybindings
vmap <C-C> "+yi
imap <C-V> <ESC>"+gPi
" Insert mode navigation
imap <C-J> <Down>
imap <C-K> <Up>
imap <C-H> <Left>
imap <C-L> <Right>

" Maximize window
if has("gui_running")
    set lines=999
    set columns=999
endif

" Hide toolbar in gui
set guioptions-=T

" NERDTree mapping
map <C-t> :NERDTreeToggle<CR>

set nu "Line numbers
set fileencodings=utf8,cp1251 "Encoding order

map ё `
map й q
map ц w
map у e
map к r
map е t
map н y
map г u
map ш i
map щ o
map з p
map х [
map ъ ]
map ф a
map ы s
map в d
map а f
map п g
map р h
map о j
map л k
map д l
map ж ;
map э '
map я z
map ч x
map с c
map м v
map и b
map т n
map ь m
map б ,
map ю .
map Ё ~
map Й Q
map Ц W
map У E
map К R
map Е T
map Н Y
map Г U
map Ш I
map Щ O
map З P
map Х {
map Ъ }
map Ф A
map Ы S
map В D
map А F
map П G
map Р H
map О J
map Л K
map Д L
map Ж :
map Э "
map Я Z
map Ч X
map С C
map М V
map И B
map Т N
map Ь M
map Б <
map Ю >
