- name: My first play
  hosts: local
  connection: local
  tasks:
   - name: Update package cache
     become: true
     ansible.builtin.apt:
       update_cache: true

   - name: Install required packages
     become: true
     ansible.builtin.apt:
       pkg:
         - curl
         - git
         - iotop
         - htop
         - mc
         - ncdu
         - nmap
         - p7zip
         - pv
         - tig
         - tmux
         - vim
         - zsh
         - whois

   - name: Checkout ecosystem repository
     ansible.builtin.git:
       repo: git@github.com:alexey-chernikov/ecosystem
       dest: ~/.ecosystem
       force: no
