- name: My first play
  hosts: local
  connection: local
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
      msg: Hello world

   - name: Update package cache
     ansible.builtin.apt:
       update_cache: true

   - name: Install required packages
     ansible.builtin.apt:
       pkg:
         - curl
         - git
         - iotop
         - htop
         - mc
         - ncdu
         - nmap
         - p7zip
         - pv
         - tig
         - tmux
         - vim
         - zsh
         - whois
