# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/alex/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Powerlevek9k Themes
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context ssh dir rvm vcs newline root_indicator)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs history time)
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_RVM_BACKGROUND="red"
POWERLEVEL9K_NODE_VERSION_BACKGROUND="yellow"
POWERLEVEL9K_NODE_VERSION_FOREGROUND="black"

POWERLEVEL9K_MODE='nerdfont-complete'
source  /usr/share/powerlevel9k/powerlevel9k.zsh-theme

# Aliases
alias ls='ls --color'
alias la='ls -la'
alias rnab='yarn run beta-android'
alias rnib='yarn run beta-ios'
alias rp='. rp'

export PATH=~/.bin:$PATH

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" 
