# Install/refresh microk8s for specific version

- name: Install required apt packages
  ansible.builtin.apt:
    pkg:
      - nfs-common

- name: Install microk8s
  become: yes
  community.general.snap:
    name: microk8s
    classic: true
    channel: "{{ k8s_version }}/stable"

