[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function
[[ -r ~/.bashrc ]] && . ~/.bashrc

export PATH=~/bin/Sencha/Cmd/5.1.2.52:$PATH

export SENCHA_CMD_3_0_0="~/bin/Sencha/Cmd/5.1.2.52"
